#!/usr/bin/env python3
"""Merge the vendor TSV return (id<TAB>translation) into src/locale/messages.<lang>.xlf.

Usage: tools/i18n/merge-xlf.py es
Reads src/locale/messages.xlf (from `npm run i18n:extract`) and tools/i18n/<lang>.tsv, writes
src/locale/messages.<lang>.xlf. Untranslated units keep the English source with
state="needs-translation" so the build warns rather than fails (i18nMissingTranslation: warning).
Placeholders in the TSV are {0}, {1}... in the order the <x/> elements appear in the source.
Owner: retail-digital. Vendor round-trips are tracked in MOL-2214.
"""
import re
import sys
from pathlib import Path

lang = sys.argv[1] if len(sys.argv) > 1 else 'es'
root = Path(__file__).resolve().parents[2]
src = (root / 'src/locale/messages.xlf').read_text(encoding='utf-8')
tsv = {}
for line in (root / f'tools/i18n/{lang}.tsv').read_text(encoding='utf-8').splitlines():
    if not line.strip() or line.startswith('#'):
        continue
    k, _, v = line.partition('\t')
    tsv[k.strip()] = v.strip()

missing = []

def unit(m):
    ident, attrs, body = m.group(1), m.group(2), m.group(3)
    sm = re.search(r'<source>(.*?)</source>', body, re.S)
    source = sm.group(1)
    ph = re.findall(r'<x [^>]*/>', source)
    if ident in tsv:
        t = tsv[ident]
        for n, p in enumerate(ph):
            t = t.replace('{%d}' % n, p)
        target = f'<target state="translated">{t}</target>'
    else:
        missing.append(ident)
        target = f'<target state="needs-translation">{source}</target>'
    body = body.replace(sm.group(0), sm.group(0) + '\n        ' + target, 1)
    return f'<trans-unit id="{ident}"{attrs}>{body}</trans-unit>'

banner = (f'<!-- messages.{lang}.xlf is generated by tools/i18n/merge-xlf.py from the vendor TSV return. '
          'Do not hand edit; re-run the merge after `npm run i18n:extract` (MOL-3122). -->\n')
out = re.sub(r'<trans-unit id="([^"]+)"([^>]*)>(.*?)</trans-unit>', unit, src, flags=re.S)
out = out.replace('<file source-language="en-US"', f'<file source-language="en-US" target-language="{lang}"', 1)
out = out.replace('<xliff ', banner + '<xliff ', 1)
(root / f'src/locale/messages.{lang}.xlf').write_text(out, encoding='utf-8')
print(f'{len(tsv)} translations applied, {len(missing)} left needs-translation')
for m in missing:
    print('  ', m)
